/**
 * introduce class like html class<br>
 *
 * Name : xxx<br>
 * Date : 2018-08-16<br>
*/

public class Comments{
  public static void main(String[] args){
    System.out.println("Comments Test");
    // System.out.println("Comments Test");
    /*
    very boring time... i think this time is so meaningless

    */
  }
}
// ** create java documents **
// C:\KOSTA187\workspace\1. Java\day01>javadoc Comments.java
// Loading source file Comments.java...
// Constructing Javadoc information...
// Standard Doclet version 1.8.0_181
// Building tree for all the packages and classes...
// Generating .\Comments.html...
// Generating .\package-frame.html...
// Generating .\package-summary.html...
// Generating .\package-tree.html...
// Generating .\constant-values.html...
// Building index for all the packages and classes...
// Generating .\overview-tree.html...
// Generating .\index-all.html...
// Generating .\deprecated-list.html...
// Building index for all classes...
// Generating .\allclasses-frame.html...
// Generating .\allclasses-noframe.html...
// Generating .\index.html...
// Generating .\help-doc.html...
